### ISSUE TITLE
Incorrect Offers percentage calculation

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#106]
I've created a **Product to Product** offer for a 47% discount on the **HTC**, if you buy the **Mac**.
As you can see, the price is **$122** and the 47% discount should be **-$57.34**.
However, the cart doesn't calculate the percentage correctly, as the result is -$56.42
![offer](https://user-images.githubusercontent.com/3336728/34961486-0580cf42-fa48-11e7-9e39-7585367e7135.png)

Also, for the **Fixed Value** discount, if I set a $20 discount, the cart shows **-$26**.

Where in the code, does this calculus take place, so i can have a look at it?
The logic should be easy: get the total price of the product (tax included) and apply the discount.

**Comment by villagedefrance** [comment]
What type of offer did you select? Product to Category?
At this time, when using a Category, the lowest Price in that Category gets applied, not the actual Price of the Product in that Category. This might explain why the result is wrong. This is why I initially wanted to remove the Offers system all together a few weeks ago. So I am aware of the limitations.
Product to Product and Category to Product should work fine but not the other 2 types.
The file is catalog>model>total>offers.php

**Comment by Tangol** [comment]
The selected offer in the test, was **Product to Product**.

This isn't really a good reason to remove the entire feature, as everything can be fixed/tweaked.

**Comment by villagedefrance** [comment]
I just realized today that the most likely reason for the discrepancies in the discount totals has to be the "Eco-tax". Basically the formulae is somewhat correct in taking into account All the taxes, and then applies the offer discount to Them, this is good and bad because We expect to see only the product (VAT) being removed and none of the other taxes. ... mmmmh ... suggestions anyone?

**Comment by Tangol** [comment]
Indeed, the reason is the **Eco Tax**.
In our case, it seems that the formula takes into account the **Eco Tax (-$2)**, so the total price of the individual product, isn't the one shown (**$122**), but **$120**.
So **$122 (VAT Included) - $2 (Eco) = $120 - 47% = $56.42 Discount**

The result is correct, but the end user needs to see all these taxes being applied.
Because if we just look at what the offer and the cart show us, we get that if we buy the Mac, we have a 47% discount on the HTC ($122), and that discount should be **-$57.34**.

Now this leads us to the other problem.
Why is tax (VAT/Eco ?) being applied on the fixed value discount?
If i set a $20 discount, I would like to see -$20 off the product price, not some modified-including taxes value.

**Comment by villagedefrance** [comment]
As far as I can tell all calculations are now correct.
The Eco Tax is actually +2.00 so that's correct too.
Fixed value or Percentage value Discounts must be treated the same and I strongly believe that they should have the taxes applied otherwise the invoicing will be wrong.
So in the example above the discount you wish to apply should be entered excluding tax so it will display as $20.00 (including taxes) in the Cart. So should be $15.00 in the Offer?

**Comment by villagedefrance** [comment]
I added a new option in "Extension > Totals > Offers" to apply (or not) corresponding product taxes to offer discount values. However, this is a global Setting and will apply to every single offer, so the solution of entering discount values excluding taxes as described in my previous comment is still valid, if some of the offers do require taxes applied.
I think that all issues have now been fixed with this last commit.

**Comment by Tangol** [comment]
It works ok now, however I have a small observation.

![offer](https://user-images.githubusercontent.com/3336728/39407718-0c4c62fa-4bd3-11e8-8868-95312cb734f1.png)

As you can see, when an offer is active, the **Total** price doesn't return the value with the offer included and it should, as some customers may get confused regarding the real price they will pay.

Also, the sort order, when offers/discounts/vouchers etc. are applied should be:
- **Sub-Total:**
- **Eco Tax (+2.00):**
- **VAT (20%):**
- **Offers/Coupons/Voucher:**
- **Total:** Total price should be the last, with all taxes, discounts etc. included.

PS: the above also applies to the **Invoices**.

Thanks!

**Comment by villagedefrance** [comment]
The "Sort Order" for each total can be changed for each "Total" extension (as per default).
