### ISSUE TITLE
Low Stock @ Admin Notifications

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#135]
Please note that the **Low Stock** filter doesn't work as it should.

It should only return the products that are low in stock (right now it shows all products).
I guess we should set a threshold between 1-9.
So whenever the total stock quantity hits 9 or lower, the Low Stock alert is triggered and the products appear in the list.
Ref https://github.com/villagedefrance/OpenCart-Overclocked/commit/a1baa0f8ddb2654320bf5f7fe1fe080e2647fb9c

Tested on https://github.com/villagedefrance/OpenCart-Overclocked/commit/fe8351ef2298f78e7d2d9a7bd5a8abf74106c920

**Comment by villagedefrance** [comment]
That's exactly what I did!
The trouble is that the URL link for filtering between 1 AND 9 doesn't exists, so the only option was to Sort by Quantity Ascending (Lowest first), and that's why it returns everything. I wasn't going to put this initially (because of precisely that) but then I thought that it would be a useful thing to have.
So I cannot accept this as an issue because it does work as expected.

**Comment by Tangol** [comment]
Alright, got it.

Also, wouldn't it be better to show the  **Home :: Products Stock Report**  page, when viewing the **Out of stock** and **Low stock** reports?
`route=report/product_quantity`

Right now, it takes us to the **Products** page.

Thanks!

**Comment by villagedefrance** [comment]
That's a good point.
... but then you still have to click again to go to the Product Page to act on it.
Still, I'm going to have a look.

**Comment by Tangol** [comment]
You don't have to click back, as you have the **View** button next to the product, that takes you straight to the product details.
So it's perfect :D

**Comment by villagedefrance** [comment]
Ok, sounds good, I will change that.

**Comment by Tangol** [comment]
Works as it should.
Can be closed.

Thanks!
