### ISSUE TITLE
Slider Modules

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#148]
I've noticed that right now, the modules that contain sliders, use different slider options.
So we have:
- **Banner**: Powered by Cycle Lite v1.0.0 (not responsive)
- **Carousel**: Powered by Slick v1.8.1 (fully responsive)
- **Slideshow**: Powered by Camera v1.3.4 (not responsive)

My question is, why not use the same slider for all modules?
**[Slick v1.8.1](http://kenwheeler.github.io/slick/)** would be the preferred option here, as it's fully responsive and touch swipe enabled.
[Example](https://demo.phpprobid.com/) of how a homepage slider (slick) should look like.

Also, the main options for each module should be:
- Slider Duration
- Slider Speed
- Select Transitions
- Select Controls Color (only for Carousel and Slideshow)
- Image [Shuffler/Randomizer](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=3546) option

This change would wonderfully complement https://github.com/villagedefrance/OpenCart-Overclocked/commit/daf21723f31b6e383e816d876dfbd8bf52f96bb4

PS: Using only **Slick** and removing the other 2 options, also improves the site performance, as we don't need to load the resources on every page.
`<script type="text/javascript" src="catalog/view/javascript/jquery/camera/camera.min.js"></script>`
`<script type="text/javascript" src="catalog/view/javascript/jquery/cycle/jquery.cycle.min.js"></script>`

Thanks!

**Comment by villagedefrance** [comment]
Ok, I agree some of the scripts need an update because they are too old, not maintained anymore or not responsive.

Now I have modified "Banner", "Carousel" and "Slideshow to work with Slick.js.
Sadly the result is not brilliant because Slick.js is mostly a Carousel and although it can be used as a slider, it doesn't do that very well. The other thing is that all 3 modules have to share the same CSS, which is not great when 2 or more modules are on the same page because the last CSS loaded takes over and compromises the previous one. I tried to unify (and minify) the css to work with all 3 modules but this results in some jittering on page load. Not cool.

I am going to commit my changes so far so you will be able to see for yourself.

... but I am going to change all that right-away probably by using Flexslider.js for "Slideshow" and something else for "Banner" (not sure yet what. Unslider.js?).

The idea of having 1 single script for all sliders makes a lot of sense in many ways, but the trade-off is unstability and css issues. I think the way forward is to find and use the best scripts for each job, as this will prevent clashes and gives the best results.

**Comment by Tangol** [comment]
After the latest commit we get an error and the homepage doesn't load anymore.
 `2018-03-08 10:13:18 - PHP Notice: Undefined index: auto in C:\Bitnami\wampstack-7.0.22-1\apache2\htdocs\oce\catalog\controller\module\slideshow.php on line 54` 

So I guess you are right, there's no point in using the same slider for all modules, better to distribute the load.
[FlexSlider 2](http://flexslider.woothemes.com/) and [Unslider](https://github.com/idiot/unslider/releases) both look amazing and are up to date.

**Comment by villagedefrance** [comment]
Ok, I've just changed "Slideshow" and "Banner" to use Flexslider 2.
I still have to update the Install SQL data with the changed module Settings tomorrow, but before I do that, I am asking for your feedback.
I am very happy with the changes and I can't see any issues ... but we never know.
Thank you.

**Comment by Tangol** [comment]
You've really outdone yourself this time Philippe.
The new sliders work/look amazing.

Issue can be closed.

Thanks a lot!
