### ISSUE TITLE
Uninstall Module Issue

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#151]
When you try to **Uninstall** a module, the dialog box weirdly shows up twice, one on top of the other.

![uninstall](https://user-images.githubusercontent.com/3336728/37221363-50920650-23d2-11e8-9b9d-e7128ebf0942.jpg)

It works fine for **Delete**, at Users, Products etc.

![usr](https://user-images.githubusercontent.com/3336728/37221881-f40f74a6-23d3-11e8-9c0a-94c274281124.jpg)

Tested on https://github.com/villagedefrance/OpenCart-Overclocked/commit/33b66b969e3f5e2670d044682dde840e637f3b34

**Comment by villagedefrance** [comment]
This is not an issue!
This is the normal behavior for all extensions: Modules, Modifications, Payments, Shipping, Themes, Totals, Fraud, Feeds.

Like before, there are 2 distinct functions: One to deal with List Delete Action and One to deal with Extensions Uninstall. While before the Dialog boxes where almost identical, with [jQuery Confirm](http://craftpip.github.io/jquery-confirm/) they are different because for extensions, in order to pass a Redirect URL as data, you need to capture the URL first! This means using 2 jQuery functions: the first displays the Dialog box with the warning message while the seconds (with no message) does the background work by capturing the URL and then executes the redirection once the Dialog box has been answered. The Delete function doesn't need 2 boxes because it performs a POST request directly in the same controller.

I have read the jQuery Confirm documentation extensively to find a single dialog box method, but this is what is recommended to do in this situation and I couldn't find a better way.
It does work great every time but 2 clicks are required, unfortunately.

All in all, the old Javascript code in the Header was truly obsolete by today's standards and had to go. The jQuery Confirm script is a much modern approach, looks better, is animated, is themable (if required) and can answer any type of Dialog boxes requirements we may need in the future (like contextual help for example).

I am, as always, open to suggestions but I think, in this case, the issue should be closed because it is technically working reliably and I doubt we are going to find a better answer.

**Comment by Tangol** [comment]
Alright, got it.

Can be closed.
