### ISSUE TITLE
Specials & Discounts Issue

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#155]
- If let's say by mistake, you add discounts/specials to all products in the store - there's no way to revert/remove them.

This is a **HUGE** issue, as you may have thousands of products available and sometimes you get a new employee that doesn't know what he's doing and **BAM!** - discounting all products in the store, would be catastrophic...

I suggest adding a new button **Remove Specials/Discounts**, that would open a dialog box with 2 checkboxes Specials & Discounts, so the user can select either one or both a the same time, and an option for all products or only the selected ones.
This would give us the ability to quickly remove any specials/offers at any given time.

![remove](https://user-images.githubusercontent.com/3336728/37437860-0a32c544-27f8-11e8-8b36-183ae15b8cfc.jpg)

- Also, the system doesn't let us add custom discounts/specials, only multiple of 5. (5%, 10%, 15% ...).
This is bad, as a supplier may give you (the store) a discount of 17% on a product, but you can only apply either 15% or 20%.
So instead of `Discount Price`, we should have `Discount Percentage (%):` and the box should let us insert a custom value, as a number (10, 13, 48 etc.) - the same would work for Specials.

![disc](https://user-images.githubusercontent.com/3336728/37436646-8b58097e-27f1-11e8-9c3d-915c71cf349d.jpg)

**Comment by villagedefrance** [comment]
I have changed the price increments to 1 instead of 5 for Specials and Discounts Quick Tools.
I also added a new option in Settings (Preference tab) where the Quick Tools (and possibly other things in the future) can be made available to only specific User Groups.
I have considered the suggestion of adding an extra button to cancel changes, but this is not technically feasible as far as I can tell. Also to remember that these buttons are only Quick Tools and not the recommended way of creating Specials and Discounts, which is through each individual product.
I consider this issue resolved.
