### ISSUE TITLE
Store Name in Invoices

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#160]
Please note that the **Store Name** doesn't get updated in the **Pick List**, **Delivery Note**, **Invoice**, **Order Details**.

![sname](https://user-images.githubusercontent.com/3336728/37572157-c87ccd96-2b0f-11e8-9b38-c2659cce7b2b.jpg)

It only works ok for the **Personal Data**.

![data](https://user-images.githubusercontent.com/3336728/37572179-fefea164-2b0f-11e8-909b-578cd3c8bd5a.jpg)

Tested on https://github.com/villagedefrance/OpenCart-Overclocked/commit/aee2e52b359f2fc63c93fac5eac1976c20616bf0

**Comment by villagedefrance** [comment]
Technically speaking the issue is the opposite: the Personal Data is incorrect because it displays the General Store name instead of the Individual Store name (Multi-store name).
However, saying that, I have changed the Admin documents to show the General store name (like in Personal Data) because I think it makes more sense for accounting purposes, the company being registered under that name, not the individual Multi-store names.

**Comment by Tangol** [comment]
Now it works fine.

The issue can be closed.
Thanks!
