### ISSUE TITLE
Add to Cart / Pre-order buttons

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#167]
Please note that the **Add to Cart / Pre-order** buttons should be added back to the main theme, as it was on **v1.10.2 (OCE)**, as it enhances the user experience.

![cart](https://user-images.githubusercontent.com/3336728/37980048-ce9bb568-31f2-11e8-863f-8b7d132f796e.jpg)

Thanks!

**Comment by villagedefrance** [comment]
I think the commit above is the most logical answer to this.

**Comment by Tangol** [comment]
It still doesn't work.
No **Add to Cart / Pre-order** buttons are shown.

![cart](https://user-images.githubusercontent.com/3336728/37994986-d1dd4484-321b-11e8-95ed-481085330b87.jpg)

**Comment by villagedefrance** [comment]
The pre-order button depends on the default stock status defined in Settings. If set to out-of-stock it will not show. If set to pre-order it should.

**Comment by Tangol** [comment]
Stock status set to **Pre-order** and it still doesn't work...

Tested on https://github.com/villagedefrance/OpenCart-Overclocked/commit/99847a9a60469d242daa99852a7fbd2eac6ab66f

**Comment by villagedefrance** [comment]
Ok, I'm not too sure if I understand correctly what you are asking for.

As of today, following the latest commits, the code logic is 100% sound. It now takes full advantage of the Setting option "Stock Checkout" (Allows an order to be placed even if no stock is available, which is in essence a pre-order). This setting was previously Only used in the Cart/Checkout, so this is progress as it is now applied throughout.

Now, there never was a specific "Pre-order" form, even in v1.10.2, only my Quote system which is very different and product specific (option inside each Admin Product Form) and applies ideally to products "made to order". Stock statuses (out of stock, pre-order, ...) do not apply to "Quote" products obviously.

All Product Modules (Bestseller, Featured, Latest, ...) have the option of displaying the "View" button and the "Add to Cart" button. This is turned off by default because of possible age limitations in place in the store, but all buttons will show properly when selected in each module.

The "Warning" icon does not mean "Pre-order", it means "not available/cannot be ordered at this time". It is just a warning message and therefore has no link. If people still want to see the full product then they have to click the "View" button, which has a link.

I think everything makes perfect sense as it is, but maybe I have missed something. If you are referring to a specific case scenario do let me know. I am happy to push this further if required so we can cover all the angles.

**Comment by Tangol** [comment]
Ohh, I didn't know we had the **Show Add to Cart Button** option for the Bestseller, Featured, Latest products, so my bug report was regarding that matter only.

Damn, I need to learn to better describe issues!
Sorry about that.

However, your latest commits are welcomed, as they let us make a **pre-order**, a feature which was necessary.

So again, thanks a lot Philippe!
