### ISSUE TITLE
Frontend Adjustments

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#177]
Please note that the **Colorbox Privacy Policy** is not responsive.
Also, from what I've seen, Colorbox isn't responsive at all, so does it make any sense to keep using it?

![policy](https://user-images.githubusercontent.com/3336728/39627756-91603220-4faf-11e8-8427-2763b597db00.png)

Also, at the **Shopping Cart**, the **Continue Shopping** button should be moved to the far left, the same as the **Checkout** button.

![shop](https://user-images.githubusercontent.com/3336728/39627907-029d7452-4fb0-11e8-926b-31f000dd4451.png)

Tested on https://github.com/villagedefrance/OpenCart-Overclocked/commit/9279f2f77d0f1c121a48261dbd84d30146dc17f0

**Comment by villagedefrance** [comment]
I will have a look at a Colorbox alternative.

For the buttons I don't really want to move them. I understand the responsive argument behind it but I think they make much more sense where they are now.

**Comment by villagedefrance** [comment]
So, I am keeping Colorbox because it is the best tool for the job, in both Admin and Catalog.
I have however, made a new custom CSS for it, to match the jQuery Confirm modal boxes. ... much better I think. Box width is now 600px.

Note: when looking at responsive content please check the "landscape" view because some content will NEVER be efficiently displayed at 320px (portrait). i.e Terms & conditions.

**Comment by Tangol** [comment]
Looks great now.
Issue fixed, can be closed.

Thanks!
