### ISSUE TITLE
[1.7.0] Zones filter not good

### ISSUE THREAD

**Issue by gob33** [villagedefrance/OpenCart-Overclocked#22]
The problem:
After installing french regions (country_code 73) and departments (country_code 74), if i filter on "France" (73) i get the correct result BUT the pagination counts ALL zones "France" + "France Metropolitan". You can even try filter with "AL", the result is empty but pagination shows 5 tabs.
Query in getTotalZonesByCountryNames() is not good, it takes "France%" or "AL%" so adds all.
The javascript filter() should use country_id and name.
I have checked only this one and not others.

![snap1](https://cloud.githubusercontent.com/assets/4837882/9550923/6fec5976-4dae-11e5-9d62-6e548c0d45e1.png)

NOTE: It is stupid to do a DB query for the total as each $query has num_rows which IS the total. Just return the whole $query object to the controller and extract rows and total here. You can even pass a mysql error and true/false for failure like this.

**Comment by villagedefrance** [comment]
The Country filter for zones uses json autocomplete, therefore expects a FULL country name, no wildcards(%) or abbreviations (AL). So it works.
Regarding France, there is no more "France Metropolitan" (ID:73) in the database, just "France" (ID:74). Being French myself I perfectly understand the difference between both, but deliberately chose to remove the confusing "France Metropolitan" for the rest of the world in OCE. Guyane, Guadeloupe, Reunion, etc ... are classified as themselves.
In your screenshot, you have French Regions instead of French Departements, which is nice but not really useful as far as postal adresses are concerned.
I will not update OCE Install SQLs because I want to keep it clear and simple, but ID 73 is available for you to add French Regions if you need them.
