### ISSUE TITLE
Long-term Plan for OpenCart Overclocked (question)

### ISSUE THREAD

**Issue by skyosev** [villagedefrance/OpenCart-Overclocked#24]
Hi Philippe,

I'm watching OpenCart Overclocked for a while and I like very much your attitude and commitment to the project. I am willing to participate in this fork but I'm more interested in solving architecture problems than adding new features. That's why I have some general questions before taking time to create pull requests. 

Being theme and extensions developer, I have broad experience in OpenCart. It wouldn't be unfair to say that I just know it inside out. There are many things that bother me as a developer, mostly about constant violation of the DRY principle. The most striking example is with the way the language variables are assigned to the templates, with endless repetition of 
```javascript
$this->data['foo'] = $this->language->get('foo');
```
I know that the OpenCart's philosophy is being simple and not trying to make JAVA from PHP, like Magento does, but there are many things that can be improved. 

I would like to know a bit more about your idea behind Overclocked:

- Do you strive to adhere as much as possible to the OpenCart way without changing things that could eventually break some third party extensions, i.e.  without improving the underlying platform ?
- You may also want to keep maximum OC compatibility in Overclocked 1.x branch and create 2.x branch with some backwards compatibility breaks? 
- Or you would like to improve the platform without introducing BC breaks, so that only new features/modules will take advantage from the improvements. For example we can create a better method for assigning language variables, but make only new Overclocked modules (Custom Menu System, Custom Footer System etc.) use it.

I would propose some things based on your answers of my questions. If anything is unclear, let me know.

Thank you for your time.
Regards, 
Stoyan

**Comment by villagedefrance** [comment]
Hi Stoyan,

Thank you for your interest in my Overclocked Edition.
I know your commitment to the official OpenCart project through the forums and Github, and your extended knowledge of the code through some of your contributions. So, I think I understand your questions and where you are coming from.

Even though I am doing my own version, I have to say that I am also fully commited to the official branch, but like many of us who can write codes, I am also fully aware that v2.x is too buggy and far from having reached maturity. My Overclocked Edition tries to compensate for this.

As described in the OpenCart Overclocked Edition presentation page here on Github, the main objectives are:
- Strictly follow the official OpenCart Coding Standards.
- Improve ergonomy to help shop owners with their daily activities.
- Keep the code pure (no framework or template engines).
- Improve routines and queries to reduce page loading.
- Fix as many bugs as possible.
- Update scripts and libraries to latest.
- Try to preserve compatibility with older browsers.
- Limit external connections (like Google fonts or Google captcha).

So, to answer your question about backward compatibility, the answer is: 
I don't mind breaking backward compatibility.
What is important is to make changes for the better, to improve the MVC flow, the user experience, the page loading time, the database requests, etc... and major core changes should be properly implemented, with a new distinct version number, as I did moving from v1.6.5 to v1.7.0.

Please note that OpenCart Overclocked Edition will Never go beyond v1.9.9, because I have agreed with Daniel Kerr that OCE will not compete with v2.x. That means that, when the time comes, I will have to decide which way to go with the OCE name and versionning.

I would be honoured if you choose to join the Overclocked Edition project. I haven't yet added admin users to my Github but it can't be that hard. It all depends on what level of involvement you wish to have I suppose.

Email: contact@villagedefrance.net

**Comment by IP-CAM** [comment]
well spoken, Philippe !

**Comment by skyosev** [comment]
Thank you for your answer. I think it pretty much covers everything i needed to know.
I'll start with some performance related pull requests that are just minimal changes to existing functionality. 

Best Regards!
