### ISSUE TITLE
Meta Tag Description  in Admin

### ISSUE THREAD

**Issue by discoverytdi** [villagedefrance/OpenCart-Overclocked#37]
Hi in the process of moving my store and have found that when I place a Meta Tag Description in the categories and products page save then re-open the page the Meta Tag Description disappears. thought it might be and error in  my installation so created a a fresh install with the data that came with the package with no changes made and the same issue is present.
Peter

**Comment by villagedefrance** [comment]
Yup, I confirm your findings and I have found the fix for it, which I'm going to commit in a minute.
The bug is in the script, where this line:
$('#meta-description<?php echo $language['language_id']; ?>').val('');
Must be removed (otherwise it calls an empty value everytime)
This affects: product_form, category_form, information_form and news_form.
Thank you for reporting it.

**Comment by discoverytdi** [comment]
Glad to have helped keep up the good work.
Peter
