### ISSUE TITLE
[1.7.2] New classes broke extensions usage

### ISSUE THREAD

**Issue by gob33** [villagedefrance/OpenCart-Overclocked#38]
I would like to point out that in forms with an image field and/or multiple select (select all / unselect)
the new code introduced with 1.7.2 is not compatible with old versions when writing an extension.
If someone adopts the new code with class=... in his extension, this will not display if extension used with version <= 1.7.1
Developper will have to make a choice, continue with old code and text links (compatible) or use graphical 1.7.2 buttons (incompatible with <=1.7.1).
```
<a onclick="image_upload('image', 'thumb');" class="button-browse"></a><a onclick="$('#thumb').attr('src', '<?php echo $no_image; ?>'); $('#image').attr('value', '');" class="button-recycle"></a>
```

**Comment by villagedefrance** [comment]
The new code is only slightly modified to use CSS, but the script is exactly the same, so it is still compatible: Just remove the 'class="button-browse"' and 'class="button-recycle"' and put the old text definitions and it will work fine.
The question wether or not developers have to make a choice is not the real question. The real question is if they want to make their extension easier to use on tablets (which is why the new code with buttons, instead of text, was introduced in v1.7.2) or not. I think we all agree that the new version much more intuitive and doesn't require language definitions. bonus.
The thing is the code has to move on, each version will obviously bring new ways of doing stuff, that's progress and we can't stop it.

**Comment by gob33** [comment]
Ya, but i tempted to make a port of one of my Oc extensions. Modification is graphically nice but that point would force me to publish 2 versions: one for OCE<=1.7.1, one for OCE>=1.7.2 with very very few differences. Or declare it compatible only with >= 1.7.2.
It like differences between OC2.0.3.1 and OC2.1.0.1 force one version for each.
A chance is that software not used by tons of merchants so that you can evolve without contraints.
