### ISSUE TITLE
[1.7.4] EU taxes works only in English

### ISSUE THREAD

**Issue by gob33** [villagedefrance/OpenCart-Overclocked#40]
As EU taxes installs its own table 'eucountry_description', it is not touched when adding/removing a new language, so that it displays no EU country (empty result) when admin is in another language than English.
Should it be part if the core ? I see it rather as an extension, or you must rewite it.

**Comment by villagedefrance** [comment]
OCE is meant to be International, not just European, so EU taxes are optional. Also EU Taxes are ONLY for Digital Goods, not manufactured products, so again optional in most cases.
Like OpenBay and vQmod, it is a modification only.
I added it because I had a request for such extension over a year ago, for which I made a module in English and French. Sadly I don't speak German, Greek, Portuguese or Dutch ... so to be fair to everyone, I only provided the English SQL in OCE as a reference and descriptions can be manually adjusted for each language.
This is also something the OpenCart Team always refused to implement (like the Cookie Policy) in the official releases, probably because it is too localised for them, and they want to remain fully International. So I added it as a bonus, a time saver for developers in Europe.

**Comment by gob33** [comment]
Yes I understand usage but it is not fully integrated into the core.
For that, its tables should be in opencart.sql, not in the install() function.
Like that when installing a new language, descriptions are duplicated and not being inexistant.
