### ISSUE TITLE
[1.8.0.beta] Remarks about Affiliates

### ISSUE THREAD

**Issue by gob33** [villagedefrance/OpenCart-Overclocked#68]
1) You have put setting 'config_login_attempts' in affiliates header, but in oc2.x it is common with customers and put in 'accounts'

2) As 'error' is an array, it is syntaxly best to write:
```
return empty($this->error);
```
than negate like
```
if (!$this->error) {
return true;
} else {
return false;
}
```
3) As oc1.5x, you always use 
```
$this->language->load(...)
```
but the good form is
```
$this->load->language(...)
$this->load->model(...)
```
(the loader loads a language file)

4) The method 'addActivity' is correct but I prefer like oc2.x because passing an array to the method is best when extensions add some parameters here. You simply add entries inside the array and dont have to add a list of functions parameters. So i think it is bad as you have modified.
```
-			$this->model_affiliate_activity->addActivity('edit', $activity_data);
+				$this->model_affiliate_activity->addActivity($affiliate_id, 'edit', $affiliate_name);
```

**Comment by villagedefrance** [comment]
I understand what you are rightly saying and I did consider keeping your changes but I had to adjust some of them for the following reasons:

OCE is not intended to copy OC 2.x like for like. I believe that some implementations in OC 2.x are good but many others are not that great. The objective in OCE is to add the good OC 2.x implementations, but using the OC 1.5.6.x ways. It is also essential to keep changes coherent accross the entire package, so sometimes the longer code has to be preferred over the better code. Saying that, future commit could see the better code implemented later ...

Going through your points:
1) I don't really want to have "login attempts" for customers. I think it does make sense for affiliate but not for customers IMO. This is why I moved the setting down in the Affiliate bit.
2) The "error" code you used is better, agreed, but it is not consistent with the rest of the files in the package at this time. ... I might change that in the future accross all files.
3) the "language->load" is the correct method used in v1.5.6.* (as opposed to the model loader), but you are right to say that not all v1.5.x use it, since Daniel changed it many times. For continuity I will keep this as the correct way for now, but I will do some testing because it is like you say in v2.x.
4) This method took me 3 hours to fix as it wasn't working. There was too many nagging issues with it: the most annoying was the use of "vsprintf" which is not Php 5.3.x compatible (Php 5.4+), then the json "$data" wasn't really useful since the only real data needed in there is "affiliate_id" and "affiliate_name". I can't think of any other data that would benefit from the json encode/decode. The term "data" is also a reserved term in MySql (like "key") which I try not to use, this is why I replaced it with "name" in the tables". So I decided to make it simpler, easier to write to and extract from the db, and 100% reliable.

Ultimately, all the new affiliate features are working correctly in OCE and that's the main thing.

I am as always grateful for your contributions and feedback.

**Comment by gob33** [comment]
1) 2) 3) ok
4) Im just speaking of passing the method parameters not its code, in the case when an extension developper needs to patch it througu vqmod
```
addActivity('edit', $activity_data) <= always same code as params inside the array
addActivity($affiliate_id, 'edit', $affiliate_name, $param1, $param2,....) <= need to introduce parameters
```
The first form is easier.

**Comment by skyosev** [comment]
Code like 
```php
if (!$this->error) {
  return true;
} else {
  return false;
}
```
is really annoying and cause me cold shivers every time I see it . The problem is that OC codebase is full with snippets like this (and even worse ones). Fixing all of them would require a serious overhaul, so I guess they should be left for now. My 50 cents.

**Comment by villagedefrance** [comment]
You are both right regarding the "error" code.
I will try to go through all the files at some point, to replace all occurences with:
`return empty($this->error);`
