### ISSUE TITLE
Dependencies Update

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#92]
Please note that for the next version of OpenCart-Overclocked, there are some dependencies that need updating:
- ~~[CKEditor](https://github.com/ckeditor/ckeditor-releases/releases)~~
- ~~[html5shiv](https://github.com/aFarkas/html5shiv/releases)~~
- ~~[slick carousel](https://github.com/kenwheeler/slick/releases)~~
- ~~[plyr](https://github.com/sampotts/plyr/releases)~~
- [Magnific-Popup](https://github.com/dimsemenov/Magnific-Popup/releases)
- ~~[colorbox](https://github.com/jackmoore/colorbox/releases)~~
- [jsTree](https://github.com/vakata/jstree/releases)
- ~~[DomPDF](https://github.com/dompdf/dompdf/releases)~~
- ~~[Plupload](https://github.com/moxiecode/plupload/releases)~~
- ~~[jQuery Migrate](https://github.com/jquery/jquery-migrate/releases)~~
- ~~[jQuery](https://code.jquery.com/)~~
- ~~[FlexSlider 2](https://github.com/woocommerce/FlexSlider/releases)~~

Thanks!

**Comment by villagedefrance** [comment]
I will update as required for the next version.
Thank you.

**Comment by Tangol** [comment]
Updated the list according to the recent updates.

Thanks!

**Comment by villagedefrance** [comment]
JQuery Migrate has been updated. Since we moved on to jQuery v3.2.1, jQuery Migrate v3.0.0 has been added too.

Magnific Popup will Not be updated because the current version is heavily customized to work with OCE. I tried to implement the latest version but I didn't succeed in making it work properly. The current version works well and has been further improved. I will consider a PR on this if one is submitted.

JsTree v0.9.9 will Not be updated. I have tried many times to update this but without success. The current JsTree works fine and has been improved even more and it is now faster than ever!

DomPDF is a big beast, very time consuming. It currently works as expected and I am not planning on updating it. However, I will consider Pull Requests.

For info, Camera slider has been improved too, much improving page loading :)

I am going to leave this Issue open until the Beta is complete, just in case something else comes up.

**Comment by Tangol** [comment]
Thanks for the detailed explanation.
I've included [jQuery Migrate](https://github.com/jquery/jquery-migrate/releases), because the latest version is **3.0.1**, but you've updated to **3.0.0**.

**Comment by Tangol** [comment]
Please note that a [new version](https://ckeditor.com/blog/CKEditor-4.9-released/) of CKEditor was released.
We should update, as it fixes a bunch of issues.

Thanks!

**Comment by Tangol** [comment]
Another [version](https://github.com/ckeditor/ckeditor-releases/releases) of CKEditor was released, fixing an important bug.
Update needed.

Thanks!

**Comment by villagedefrance** [comment]
The only fix in v4.9.1 is the following, which as nothing to do with us since we do not use CKFinder.
I don't think an update is necessary at this time as there are no real benefits.

CKEditor 4.9.1
Mar 26/2018

Fixed Issues:

    #1835: Fixed: Integration between CKFinder and File Browser plugin does not work.

**Comment by Tangol** [comment]
Please note that [CKEditor](https://github.com/ckeditor/ckeditor-releases/releases) got updated again.

**Comment by Tangol** [comment]
I think we can close this report, as all dependencies got updated to their most stable version and everything was fine tuned to work perfectly with OpenCart Overclocked.

Thanks!
